    
    link: "Link(" link_first ")" | "Link(" link_first ", " link_rest ")" | "Link(" link ")"
    
    ?link_first:  NUMBER 
    
    ?link_rest: link
    
    %ignore /\s+/
    %import common.NUMBER


    
    tree_node: "Tree(" label ")" | "Tree(" label ", [" branches "])"
    
    
    ?label: NUMBER
    
    branches: tree_node (", " tree_node)*
    
    %ignore /\s+/
    %import common.NUMBER

